### ISSUE TITLE
SAI Comments not triggering a diff

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/Keira3#2467] opened 2023-09-17 19:56 UTC
If you update a SAI script with only Generate comments it will not provide a new diff and the new comment will not be updated. You need to change an actual param for the comment to update in the diff

**Comment by sudlud** [comment] 2023-11-19 12:34
can confirm on Keira 3.5.4

**Comment by FrancescoBorzi** [comment] 2023-12-25 15:44
I can also confirm it is happening on latest master (rev https://github.com/azerothcore/Keira3/commit/bbb461df81562fe6d7aadf29012a418fb725d1f6 ), it only happens for the first time. After the diff is updated once, then it will work fine.

Not sure what the cause of the problem is. Needs further investigation.

**Comment by sudlud** [comment] 2024-02-18 05:35
Still present on Keira 3.6.1 🐞

**Comment by Helias** [comment] 2024-03-17 00:19
fixed in https://github.com/azerothcore/Keira3/pull/2819

**Closed** 2024-03-17 14:58 UTC
Labels: bug, Priority-High
