### ISSUE TITLE
Suggestion: Data replication

### ISSUE THREAD

**Issue by CDK-Github** [azerothcore/Keira3#700] opened 2020-05-20 13:23 UTC
Hello Keira3's team,

It would be interesting and practical to be able to create a new entry of a gameobject/creature/item based on another entryID by duplication of data.

What do you think?

Thank you for your great work!

**Comment by Helias** [comment] 2020-05-20 13:25
Hello, thank you for your suggestion.

Anyway I think that this issue is a duplicate of https://github.com/azerothcore/Keira3/issues/25
So I am closing this issue.

Anyway we are workng on the last release in this period, you can see our milestone here: https://github.com/azerothcore/Keira3/milestone/1

**Closed by Helias** 2020-05-20 13:25 UTC
