### ISSUE TITLE
ssh tunnel support

### ISSUE THREAD

**Issue by Romain-P** [azerothcore/Keira3#1040] opened 2021-01-10 21:56 UTC
Would a ssh tunnel support be conceivable in the future? My mysql ports are not exposed

**Comment by Helias** [comment] 2021-01-11 11:55
duplicate of https://github.com/azerothcore/Keira3/issues/93

Anyways, for now, you can follow this guide to make the ssh tunnel https://www.linode.com/docs/databases/mysql/create-an-ssh-tunnel-for-mysql-remote-access/
If we will can, we will support it natively from Keira3

**Closed by Helias** 2021-01-11 11:55 UTC
Labels: feature request
